acl_user:
    resource: "@ACLBundle/Resources/config/routing/user.yml"
    prefix:   /user

acl_new_user:
    path:     /acl/new_user
    defaults: { _controller: ACLBundle:ACL:new }

acl_user_perfil:
    path:     /acl/perfil
    defaults: { _controller: ACLBundle:ACL:perfil }

acl_homepage:
    path:     /acl/{name}
    defaults: { _controller: ACLBundle:ACL:index }

login:
    pattern:   /login
    defaults:  { _controller: ACLBundle:ACL:login }

login_check:
    pattern:   /login_check

logout:
    path:   /logout
