permisos:
    path:     /
    defaults: { _controller: "ACLBundle:Permisos:index" }

permisos_show:
    path:     /{id}/show
    defaults: { _controller: "ACLBundle:Permisos:show" }

permisos_new:
    path:     /new
    defaults: { _controller: "ACLBundle:Permisos:new" }

permisos_create:
    path:     /create
    defaults: { _controller: "ACLBundle:Permisos:create" }
    requirements: { _method: post }

permisos_edit:
    path:     /{id}/edit
    defaults: { _controller: "ACLBundle:Permisos:edit" }

permisos_update:
    path:     /{id}/update
    defaults: { _controller: "ACLBundle:Permisos:update" }
    requirements: { _method: post|put }

permisos_delete:
    path:     /{id}/delete
    defaults: { _controller: "ACLBundle:Permisos:delete" }
    requirements: { _method: post|delete }
