usuarios:
    path:     /
    defaults: { _controller: "ACLBundle:Usuarios:index" }

usuarios_show:
    path:     /{id}/show
    defaults: { _controller: "ACLBundle:Usuarios:show" }

usuarios_new:
    path:     /new
    defaults: { _controller: "ACLBundle:Usuarios:new" }

usuarios_create:
    path:     /create
    defaults: { _controller: "ACLBundle:Usuarios:create" }
    requirements: { _method: post }

usuarios_edit:
    path:     /{id}/edit
    defaults: { _controller: "ACLBundle:Usuarios:edit" }

usuarios_update:
    path:     /{id}/update
    defaults: { _controller: "ACLBundle:Usuarios:update" }
    requirements: { _method: post|put }

usuarios_delete:
    path:     /{id}/delete
    defaults: { _controller: "ACLBundle:Usuarios:delete" }
    requirements: { _method: post|delete }
